export const SET_CURRENT_VIEWER_TITLE = "SET_CURRENT_VIEWER_TITLE";
export const SET_CURRENT_VIEWER_ACTION = "SET_CURRENT_VIEWER_ACTION";
export const INITIALIZE_VIEWER = "INITIALIZE_VIEWER";
export const SET_CURRENT_STATE = "SET_CURRENT_STATE";
export const ADD_NEXT_COMPONENT = "ADD_NEXT_COMPONENT";
export const PREVIOUS = "PREVIOUS";
export const VIEW_HANDLE_CHANGE = "VIEW_HANDLE_CHANGE";
export const INITIALIZE_VIEWER_CONTENTS = "INITIALIZE_VIEWER_CONTENTS";
export const SET_CURRENT_VIEWER_TITLE_ACTION =
  "SET_CURRENT_VIEWER_TITLE_ACTION";
